# Generated by Django 3.1.7 on 2021-04-05 17:09

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_DjangoGramm', '0004_auto_20210330_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_likes', to='app_DjangoGramm.profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='image/upload/v1617642447/fqdfojw0ave5mhozuc3r.png', max_length=255, verbose_name='avatar'),
        ),
    ]
